FROM docker.io/library/alpine:edge

# Install dependencies
RUN apk add --no-cache pulseaudio librespot

# setup librespot user
ENV HOME="/home/librespot"

RUN groupadd --gid 1000 librespot \
  && useradd --uid 1000 --gid 1000 --create-home --home-dir "$HOME" librespot \
  && usermod -aG audio,pulse,pulse-access librespot \
  && chown -R librespot:librespot "$HOME"
WORKDIR "$HOME"
COPY ./pulse /etc/pulse
USER librespot

EXPOSE 3465/tcp 3465/udp

# Set the command to run the application
ENTRYPOINT ["librespot", "--backend", "pulseaudio", "--zeroconf-port", "3465", "--disable-credential-cache", "on"]
CMD ["--name", "Bar Spotify", "--autoplay", "on"]
